# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5de5778030283421959e3d5144904bc0a05406d874de9354f58760aa55eb386413ef008b90037eed6d91c16ad64ee4d15883c55b8be931b8ba90aee1d4170d36

test:
  secret_key_base: add7e56fb21c93fb4b1f3fdb9992fa59642865380312e5e48714e1d58787ef984d9190186c58dd07faad3d3ac4946852b070d9646447daf5a5f890fbf576512a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
